[project]
name = "from-pixels-to-diagnosis-ml-and-image-sequences"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "accelerate",
    "datasets",
    "evaluate",
    "pandas",
    "pytorch",
    "scikit-learn",
    "torchvision",
    "transformers",
    "wandb",
]
